// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: service.proto

#include "service.pb.h"
#include "service.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
namespace package {

static const char* KeepAliveService_method_names[] = {
  "/package.KeepAliveService/KeepAlive",
};

std::unique_ptr< KeepAliveService::Stub> KeepAliveService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< KeepAliveService::Stub> stub(new KeepAliveService::Stub(channel, options));
  return stub;
}

KeepAliveService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_KeepAlive_(KeepAliveService_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status KeepAliveService::Stub::KeepAlive(::grpc::ClientContext* context, const ::package::Empty& request, ::package::Empty* response) {
  return ::grpc::internal::BlockingUnaryCall< ::package::Empty, ::package::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_KeepAlive_, context, request, response);
}

void KeepAliveService::Stub::async::KeepAlive(::grpc::ClientContext* context, const ::package::Empty* request, ::package::Empty* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::package::Empty, ::package::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_KeepAlive_, context, request, response, std::move(f));
}

void KeepAliveService::Stub::async::KeepAlive(::grpc::ClientContext* context, const ::package::Empty* request, ::package::Empty* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_KeepAlive_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::package::Empty>* KeepAliveService::Stub::PrepareAsyncKeepAliveRaw(::grpc::ClientContext* context, const ::package::Empty& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::package::Empty, ::package::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_KeepAlive_, context, request);
}

::grpc::ClientAsyncResponseReader< ::package::Empty>* KeepAliveService::Stub::AsyncKeepAliveRaw(::grpc::ClientContext* context, const ::package::Empty& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncKeepAliveRaw(context, request, cq);
  result->StartCall();
  return result;
}

KeepAliveService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      KeepAliveService_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< KeepAliveService::Service, ::package::Empty, ::package::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](KeepAliveService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::package::Empty* req,
             ::package::Empty* resp) {
               return service->KeepAlive(ctx, req, resp);
             }, this)));
}

KeepAliveService::Service::~Service() {
}

::grpc::Status KeepAliveService::Service::KeepAlive(::grpc::ServerContext* context, const ::package::Empty* request, ::package::Empty* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace package

